"""Egress allow-list for isolated local runs (`treg run`) — the network half of the local sandbox.

The isolated `treg-run` user hides the credential from the member (a different uid). But a CLI feature
that runs member code (`gh extension`, `doppler run`) inherits the key in its environment and could send
it to an attacker over the network — a channel output-redaction can't see. This module restricts that
uid's outbound network to a fixed allow-list: the registry itself (so the runner can fetch its grant) plus
every vendor API host in the catalog (so the CLIs work). Everything else — `evil.com` — is dropped.

Option 1 (static allow-list): the set is resolved and installed ONCE at `treg setup-local-run`, not per
run. It's built from data we already have (the catalog `base_url`s + the configured registry), so it's not
a hand-maintained list. macOS enforces it with `pf` per-user rules (`user treg-run`); Linux with nftables
owner-match (`skuid`). Both are native — no bubblewrap, no proxy, no system extension.

The rule builders here are PURE (given IPs → a ruleset string) so they're unit-tested without touching the
firewall; resolution + loading live in the CLI's setup path.
"""

from __future__ import annotations

import socket
from urllib.parse import urlparse


def collect_hosts(registry_url: str | None, catalog: list[dict]) -> list[str]:
    """The hostnames treg-run is allowed to reach: the registry (for `/grant`) + every catalog vendor
    API host (so the CLIs can call their upstream). Deduped + sorted; blanks dropped."""
    hosts: set[str] = set()
    for url in [registry_url] + [e.get("base_url") for e in catalog]:
        if not url:
            continue
        host = urlparse(url if "://" in url else f"https://{url}").hostname
        if host:
            hosts.add(host)
    return sorted(hosts)


def resolve_hosts(hosts: list[str]) -> list[str]:
    """Resolve hostnames to their current IPv4/IPv6 addresses (a firewall matches packets by IP, not
    name). Unresolvable hosts are skipped — a stale entry must never brick the whole ruleset. Deduped,
    sorted. Note: CDN IPs drift, so this is refreshed by re-running setup (`--refresh-egress`)."""
    ips: set[str] = set()
    for host in hosts:
        try:
            for family, _t, _p, _c, sockaddr in socket.getaddrinfo(host, 443, proto=socket.IPPROTO_TCP):
                if family in (socket.AF_INET, socket.AF_INET6):
                    ips.add(str(sockaddr[0]))
        except (socket.gaierror, OSError):
            continue
    return sorted(ips)


def pf_ruleset(ips: list[str], user: str) -> str:
    """macOS `pf` rules scoping `user`'s egress to the allow-listed IPs on 443 (+ DNS), dropping the rest.
    Tested working on macOS 15: pf honors `user` and IP-list matches, so a rogue `curl evil.com` from the
    isolated uid is dropped at the packet level. Loopback is intentionally NOT allowed — a local listener
    would be a member-readable exfil channel."""
    v4 = [ip for ip in ips if ":" not in ip]
    v6 = [ip for ip in ips if ":" in ip]
    lines = [
        f"# treg-run egress allow-list (generated by `treg setup-local-run`) — {len(ips)} host IP(s)",
        f"pass out quick proto {{ tcp udp }} from any to any port 53 user {user}",  # DNS resolution
    ]
    if v4:
        lines.append(f"pass out quick proto tcp from any to {{ {' '.join(v4)} }} port 443 user {user}")
    if v6:
        lines.append(f"pass out quick proto tcp from any to {{ {' '.join(v6)} }} port 443 user {user}")
    lines.append(f"block drop out quick from any to any user {user}")  # everything else: dropped
    return "\n".join(lines) + "\n"


def nft_ruleset(ips: list[str], user_uid: int) -> str:
    """Linux nftables: an output chain scoping the treg-run uid's egress to the allow-listed IPs on 443
    (+ DNS + loopback for local resolvers), dropping the rest via owner-match `skuid`. Generated here;
    verified on a Linux host (this module's tests cover the string shape only)."""
    v4 = ", ".join(ip for ip in ips if ":" not in ip) or "127.0.0.1"
    return (
        "table inet treg_run_egress {\n"
        "  chain output {\n"
        "    type filter hook output priority 0; policy accept;\n"
        f"    meta skuid != {user_uid} accept\n"          # only filter the treg-run uid
        "    oifname \"lo\" accept\n"                       # loopback (local DNS resolvers)
        "    udp dport 53 accept\n    tcp dport 53 accept\n"  # DNS
        f"    ip daddr {{ {v4} }} tcp dport 443 accept\n"   # the allow-listed vendor/registry hosts
        f"    meta skuid {user_uid} drop\n"                 # everything else from this uid: dropped
        "  }\n}\n"
    )
